export const BookGenres = [
    'Fiction',
    'Non-Fiction',
    'Romance',
    'Mystery',
    'Thriller',
    'Horror',
    'Science Fiction',
    'Fantasy',
    'Historical Fiction',
    'Biography',
    'Autobiography',
    'Poetry',
    'Drama',
    'Self-Help',
    'Cookbooks',
    'Travel',
    'Children\'s Books',
    'Young Adult',
    'Comics',
    'Graphic Novels',
    'Philosophy',
    'Religion',
    'History',
    'Science',
    'Technology',
    'Business',
    'Art',
    'Architecture',
    'Photography',
    'Music',
    'Sports',
    'Adventure',
    'Western',
    'Classics',
    'Humor',
    'Satire',
    'Dystopian',
    'Magical Realism',
    'Short Stories',
    'Essays',
    'Criticism',
    'Reference',
    'Dictionary',
    'Encyclopedia',
    'Textbook',
    'Academic',
    'Scholarly'
  ];

  export const BookFormats = [
    'Print Book',
    'Hardcover',
    'Paperback',
    'Ebook',
    'Kindle Book',
    'Epub Book',
    'Audiobook',
    'Digital Audiobook',
    'Large Print Book',
    'Board Book',
    'Picture Book',
    'Graphic Novel',
    'Comic Book',
    'Magazine',
    'Textbook',
    'Anthology',
    'Collection'
  ];

  export const BookList = [
    {
      title: 'The Martian',
      author: 'Andy Weir',
      cover_front: 'https://th.bing.com/th/id/OIP.bZnbk9__Gt7bTCQfMQ9zGQHaLL?rs=1&pid=ImgDetMain',
      cover_back: 'https://th.bing.com/th/id/OIP.bZnbk9__Gt7bTCQfMQ9zGQHaLL?rs=1&pid=ImgDetMain',
      price: '14.99',
      genre_tags: ['Science Fiction', 'Adventure'],
      details: 'An astronaut stranded on Mars fights for survival and attempts to make his way back home.',
      rating: 4.5,
      book_format: 'Print Book',
    },
    {
      title: 'The Hunger Games',
      author: 'Suzanne Collins',
      cover_front: 'https://th.bing.com/th/id/OIP.bZnbk9__Gt7bTCQfMQ9zGQHaLL?rs=1&pid=ImgDetMain',
      cover_back: 'https://th.bing.com/th/id/OIP.bZnbk9__Gt7bTCQfMQ9zGQHaLL?rs=1&pid=ImgDetMain',
      price: '12.99',
      genre_tags: ['Dystopian', 'Young Adult', 'Adventure'],
      details: 'In a dystopian future, a young girl named Katniss Everdeen is forced to participate in a televised fight to the death.',
      rating: 4.2,
      book_format: 'Paperback',
    },
    {
      title: 'The Girl on the Train',
      author: 'Paula Hawkins',
      cover_front: 'https://th.bing.com/th/id/OIP.bZnbk9__Gt7bTCQfMQ9zGQHaLL?rs=1&pid=ImgDetMain',
      cover_back: 'https://th.bing.com/th/id/OIP.bZnbk9__Gt7bTCQfMQ9zGQHaLL?rs=1&pid=ImgDetMain',
      price: '9.99',
      genre_tags: ['Mystery', 'Thriller'],
      details: 'A psychological thriller about a woman who becomes entangled in a missing person investigation during her daily commute.',
      rating: 3.8,
      book_format: 'Ebook',
    },
    {
      title: 'The Alchemist',
      author: 'Paulo Coelho',
      cover_front: 'https://th.bing.com/th/id/OIP.bZnbk9__Gt7bTCQfMQ9zGQHaLL?rs=1&pid=ImgDetMain',
      cover_back: 'https://th.bing.com/th/id/OIP.bZnbk9__Gt7bTCQfMQ9zGQHaLL?rs=1&pid=ImgDetMain',
      price: '8.99',
      genre_tags: ['Fiction', 'Magical Realism'],
      details: 'A fable about a shepherd boy who travels in search of a worldly treasure and finds something more valuable.',
      rating: 4.7,
      book_format: 'Audiobook',
    },
    {
      title: 'The Power of Habit',
      author: 'Charles Duhigg',
      cover_front: 'https://th.bing.com/th/id/OIP.bZnbk9__Gt7bTCQfMQ9zGQHaLL?rs=1&pid=ImgDetMain',
      cover_back: 'https://th.bing.com/th/id/OIP.bZnbk9__Gt7bTCQfMQ9zGQHaLL?rs=1&pid=ImgDetMain',
      price: '16.99',
      genre_tags: ['Non-Fiction', 'Self-Help'],
      details: 'An exploration of the science behind habit formation and how it can be used to achieve personal and professional goals.',
      rating: 4.3,
      book_format: 'Hardcover',
    },
  ];