export const BookGenres = [
    'Fiction',
    'Non-Fiction',
    'Romance',
    'Mystery',
    'Thriller',
    'Horror',
    'Science Fiction',
    'Fantasy',
    'Historical Fiction',
    'Biography',
    'Autobiography',
    'Poetry',
    'Drama',
    'Self-Help',
    'Cookbooks',
    'Travel',
    'Children\'s Books',
    'Young Adult',
    'Comics',
    'Graphic Novels',
    'Philosophy',
    'Religion',
    'History',
    'Science',
    'Technology',
    'Business',
    'Art',
    'Architecture',
    'Photography',
    'Music',
    'Sports',
    'Adventure',
    'Western',
    'Classics',
    'Humor',
    'Satire',
    'Dystopian',
    'Magical Realism',
    'Short Stories',
    'Essays',
    'Criticism',
    'Reference',
    'Dictionary',
    'Encyclopedia',
    'Textbook',
    'Academic',
    'Scholarly'
  ];

  export const BookFormats = [
    'Print Book',
    'Hardcover',
    'Paperback',
    'Ebook',
    'Kindle Book',
    'Epub Book',
    'Audiobook',
    'Digital Audiobook',
    'Large Print Book',
    'Board Book',
    'Picture Book',
    'Graphic Novel',
    'Comic Book',
    'Magazine',
    'Textbook',
    'Anthology',
    'Collection'
  ];